### PR TITLE
refactor(syntax_highlighting): remove directly unused import

### PR DESCRIPTION
**Pull request by Green0wl**
Removed the line with the unnecessary import. Works without it.

### CODE REVIEW

**Comment by eyelash** [comment]
Thank you for opening a pull request. I'm currently reworking the syntax highlighting to be based on [prism](https://github.com/eyelash/prism) so this file will be rewritten soon :smiley:

**Comment by eyelash** [comment]
I wanted to rebase your pull request and I accidentally pushed my main onto your fork, so GitHub closed the pull request and now I don't have permission anymore to push to your fork. I guess I leave it closed now since the file will be gone soon anyway.

**Comment by Green0wl** [comment]
Did I understand correctly that you will soon add [prism](https://github.com/eyelash/prism) submodule to [platon-core](https://github.com/eyelash/platon-core) to replace the existing file with a better implementation?

I'd be happy to maintain the project. Where might you need help? I'm just starting to work with `c++`.

**Comment by eyelash** [comment]
> Did I understand correctly that you will soon add [prism](https://github.com/eyelash/prism) submodule to [platon-core](https://github.com/eyelash/platon-core) to replace the existing file with a better implementation?

Yes. Prism is quite similar to the current syntax highlighting engine of platon-core except that it can do incremental syntax highlighting (you can easily open files with hundreds of thousands of lines and get instant syntax highlighting).

> I'd be happy to maintain the project. Where might you need help? I'm just starting to work with c++.

What exactly do you want to maintain? This is just an experimental hobby project for me right now. I have some code lying around that I haven't committed yet and I have a lot of ideas in my head. I basically want to rewrite both platon-core and platon-gtk. Currently, platon-gtk is missing too many features to be actually usable as a text editor. What exactly are you interested in with regards to the project? If you're interested I can post my roadmap and maybe we can collaborate.

**Comment by Green0wl** [comment]
I am interested in everything related to `c++` development, as I am learning to code in it. I only know the base so far, but there's no stopping me). The theme of the project is also interesting, and with it everything necessary for its realization. This means that I will be interested in working on all parts of the `platon` editor. 

Yes, I will be glad to cooperate with you. Knowing your roadmap will also come in handy.

**Comment by eyelash** [comment]
# Roadmap

## prism

Prism currently only supports C and Python. The next goal is to port the languages from platon-core to prism. This should be easy since prism is basically compatible with the current syntax highlighting engine. I have some local changes in the languages that I never committed to GitHub that I'd like to go over before I move them from platon-core to prism. One example of this is the [Python strings](https://github.com/eyelash/prism/commit/f9d3efa66666589ec7891efd1f525c913cd5d187) that I never committed to platon-core.

After that I have some plans to extend the incremental highlighting to nested scopes but it is fast enough even without that so this is not high priority.

Over the long term (years and decades), I'd like to add support for many more languages.

## platon-core

The next step for platon-core is to port it to prism. I have done this locally, I just need to commit and push it.

Then I'd like to rewrite most of platon-core. I'm not really happy with the [tree](https://github.com/eyelash/platon-core/blob/1c19bf6245c359b3dcda28edd9316d17e238f55b/tree.hpp). Right now if you open a big file, it will create a big tree with many nodes. I want to write a new tree that can make use of mmap and only has one node if you open a big file. This will probably improve the performance of opening files drastically. I also want to move the JSON stuff to the C API: platon-core should have a C++ API without JSON and on top of that I can build the same C+JSON API.

I also want to rewrite the cursors with a new data structure that is similar to [what Atom does](https://github.com/atom/superstring/blob/master/src/core/marker-index.cc). I'd love to know the name for this data structure. It allows you to track an arbitrary number of positions in an editable text file with every operation in O(log n). Handling multiple cursors is not easy because inserting or deleting from one cursor possibly changes the position of other cursors.

## platon-gtk

I want to rewrite platon-gtk. I learned a lot from writing [atom-gtk](https://github.com/eyelash/atom-gtk), which is much more complete by the way. I want to get rid of Vala and write it in C++ directly. This allows me to get rid of JSON as well and just pass C++ data structures from platon-core to platon-gtk. The current version of platon-gtk is useful to test platon-core and prism in an interactive way.

In general, I probably won't have a lot of time to work on this. As I said this is just a hobby project. The goal is to write a simple text editor that uses only a few megabytes of RAM and can open and edit big files. I'm mostly interested in algorithms, data structures, the science behind text editors in general, and UX. I don't like complexity and I don't like text editors with lots of settings. You're welcome to look at the code and follow the development and I'm happy to answer questions. Since my time is limited, it will probably be difficult to collaborate on the rewrite but maybe you can help me with some features once the rewrite is done.

**Pull request closed without merging**
